### ISSUE TITLE
RAM

### ISSUE THREAD

**Issue by SamGreenwood1** [naztronaut/RaspberryPi-Website-Uptime-Monitor#5]
How much RAM does this require?

**Comment by naztronaut** [comment]
Very little RAM. My Pi Zero has 512MB of RAM and I don't think I've ever seen this go above 300MB in total (including OS and this project).

I just looked up the usage on my pi. My Pi is currently using just 95MB of RAM for everything. Most of the RAM usage is Apache, when I hop on to the UI, RAM probably jumps to maybe 200MB. 

The Python scripts only run once every few minutes and use very negligible amount of memory.

**Comment by SamGreenwood1** [comment]
Thanks.

**Comment by SamGreenwood1** [comment]
When I try to run schema.sql I get the errors shown in the attached image, how do I fix them? 

<a href="https://imgur.com/3p5SO5j"><img src="https://i.imgur.com/3p5SO5j.png" title="source: imgur.com" /></a>

**Comment by naztronaut** [comment]
Try these commands to install mariadb then try the SQL script:

```
sudo apt update && sudo apt upgrade -y
sudo apt install mariadb-server -y
```

Then you need to set a root password:

```
 sudo mysql_secure_installation
```

That will take you through the mysql installation steps. You can follow steps that look like mine below:

```
NOTE: RUNNING ALL PARTS OF THIS SCRIPT IS RECOMMENDED FOR ALL MariaDB
      SERVERS IN PRODUCTION USE!  PLEASE READ EACH STEP CAREFULLY!

In order to log into MariaDB to secure it, we'll need the current
password for the root user.  If you've just installed MariaDB, and
you haven't set the root password yet, the password will be blank,
so you should just press enter here.

Enter current password for root (enter for none):
OK, successfully used password, moving on...

Setting the root password ensures that nobody can log into the MariaDB
root user without the proper authorisation.

You already have a root password set, so you can safely answer 'n'.

Change the root password? [Y/n] y
New password:
Re-enter new password:
Password updated successfully!
Reloading privilege tables..
 ... Success!


By default, a MariaDB installation has an anonymous user, allowing anyone
to log into MariaDB without having to have a user account created for
them.  This is intended only for testing, and to make the installation
go a bit smoother.  You should remove them before moving into a
production environment.

Remove anonymous users? [Y/n] y
 ... Success!

Normally, root should only be allowed to connect from 'localhost'.  This
ensures that someone cannot guess at the root password from the network.

Disallow root login remotely? [Y/n] y
 ... Success!

By default, MariaDB comes with a database named 'test' that anyone can
access.  This is also intended only for testing, and should be removed
before moving into a production environment.

Remove test database and access to it? [Y/n] y
 - Dropping test database...
 ... Success!
 - Removing privileges on test database...
 ... Success!

Reloading the privilege tables will ensure that all changes made so far
will take effect immediately.

Reload privilege tables now? [Y/n] y
 ... Success!

Cleaning up...

All done!  If you've completed all of the above steps, your MariaDB
installation should now be secure.

Thanks for using MariaDB!
```

Then login with your new user:

```
sudo mysql -u root -p
```

Type in your newly created password when you have it. Then type:

```
mysql
```

That will enter you into the MariaDB console. Then you can run:

```
source schema.sql
```

I'll update the readme to have these steps. I forgot that not everyone will have a SQL server installed. That was a bad assumption on my part. Hope these steps help though!

**Comment by SamGreenwood1** [comment]
Is this the proper output?

<a href="https://imgur.com/PEXsaYd"><img src="https://i.imgur.com/PEXsaYd.png" title="source: imgur.com" /></a>

**Comment by SamGreenwood1** [comment]
How do I fix this?

<a href="https://imgur.com/6FsgFkb"><img src="https://i.imgur.com/6FsgFkb.png" title="source: imgur.com" /></a

**Comment by naztronaut** [comment]
Your output looks good! The database was done properly. 

Try running initCron.py script with sudo:

```
sudo python3 initCron.py
```

And in your config file, make sure your database configs are done correctly: https://github.com/naztronaut/RaspberryPi-Website-Uptime-Monitor/blob/master/config/config.sample.py

That should be renamed to config.py when you're done. The error says that access is denied for user admin, which means the credentials you provided may not be correct. This is the login for your MySQL/MariaDB installation.

**Comment by SamGreenwood1** [comment]
I'm still having trouble I've tried all of the troubleshooting steps you've provided a couple of times.

**Comment by naztronaut** [comment]
Are you still getting the access denied error? Can you double check your database credentials?  Your last error said you used the username "admin" - can you log into mysql with that username?

```
sudo mysql -u admin -p
```

**Comment by SamGreenwood1** [comment]
I don't remember, it's been a few days. I actually came back to the thread because I thought I'd posted a message since you last responded and was checking if you replied to a message I apparently hadn't posted.
