### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by SamGreenwood1** [naztronaut/RaspberryPi-Website-Uptime-Monitor#6]
I'm still having the problems that I mentioned in issue #5.

**Comment by naztronaut** [comment]
Did you double check your mysql credentials?  I don't think you ever answered my question there. You need to make sure you are using the correct database username/password combo.

**Comment by SamGreenwood1** [comment]
I've completely done everything a few times.
>

**Comment by naztronaut** [comment]
And you're still getting access denied error? 

You still haven't confirmed if you are able to log into mysql.

**Comment by SamGreenwood1** [comment]
I'm pretty sure I was.

**Comment by SamGreenwood1** [comment]
Could I connect it to a remote database?

**Comment by SamGreenwood1** [comment]
@naztronaut I'm trying again how do I determine what to set the db host as?

**Comment by naztronaut** [comment]
You can connect it to a remote db. The  Host is the hostname or IP. If you're working locally then it's "localhost" and if you're working with a remote database, you need to get the hostname or IP address for that host.

**Comment by SamGreenwood1** [comment]
Would I access it directly localhost or would it be it be on a specific port?

**Comment by naztronaut** [comment]
Default mysql port is 3306. 

This project uses the MySQLdb library. You can get more info on connecting here: https://mysqlclient.readthedocs.io/user_guide.html

Example connecting to a external server:

```python
db=_mysql.connect(host="server.com", port=3306, passwd="moonpie", db="thangs")
```

In this project, the connection is defined here: https://github.com/naztronaut/RaspberryPi-Website-Uptime-Monitor/blob/master/db.py#L6

**Comment by SamGreenwood1** [comment]
Would there be any reason that the repo would conflict with [speedtest4pi](https://github.com/mkoegel/speedtest4pi)

**Comment by naztronaut** [comment]
It's possible multiple projects on the same Pi can conflict with each other. 

I'm not familiar with the repo you listed so I can't say anything for sure.

**Comment by SamGreenwood1** [comment]
Actually now that I'm really thinking about it there wouldn't likely be a conflict in the specific situation I was thinking of since they use different databases.

**Comment by SamGreenwood1** [comment]
I'm still having issues with initCron.py.

https://imgur.com/a/3p5SO5j

**Comment by naztronaut** [comment]
Did you reset your installation? The error says that it can't find the MySQLdb library. The readme has the installation steps for the required packages:

```
pip install RPi.GPIO flask mysqlclient requests python-crontab
```

It's a different error from your previous issue, which was an authentication error with MySQL.

**Comment by SamGreenwood1** [comment]
I got this error after running that command:

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-CRie2_/mysqlclient/

**Comment by SamGreenwood1** [comment]
was I supposed to add my new password to the db.py file?

**Comment by SamGreenwood1** [comment]
I just noticed that the config file somehow reverted to its original state. I'll fix it and than see if that fixes it.

**Comment by SamGreenwood1** [comment]
nevermind I realized that I never initialized into verv

Do I need to exit verv before I initialize initCron?

**Comment by SamGreenwood1** [comment]
Now I'm getting this error when I try to initialize initCron: 

![image](https://user-images.githubusercontent.com/20076209/111370971-38f4ef00-866f-11eb-932e-30b6cb4f8258.png)

**Comment by SamGreenwood1** [comment]
I'm not using it with LEDs just for the email functionality is there a way not having LEDs connected could cause any of the errors?

**Comment by SamGreenwood1** [comment]
> Now I'm getting this error when I try to initialize initCron:
> 
> ![image](https://user-images.githubusercontent.com/20076209/111370971-38f4ef00-866f-11eb-932e-30b6cb4f8258.png)

Never mind just ran it with sudo and it gives the same SQL errors I was getting earlier.

**Comment by naztronaut** [comment]
LEDs won't cause that. That error is an 'access denied' error. Is your mysql username "admin"? And are you using the correct password?

It's a pretty simple error, you're not logging in correctly. You can try logging in directly through the cli with this command:

```
sudo mysql -u admin -p
```

Are you able to login with the credentials in config.py: https://github.com/naztronaut/RaspberryPi-Website-Uptime-Monitor/blob/master/config/config.sample.py#L23

**Comment by SamGreenwood1** [comment]
It's giving me error: 1698

when I use `mysql` it allows me in without the password is there a

**Comment by naztronaut** [comment]
That's an access denied error. 

When you use `mysql` without defining a user or password, it logs you in as root. You can login as root in the application but it's not good practice. Check out the following guide: https://raspberrytips.com/install-mariadb-raspberry-pi/

That has steps on how to create a new user. You should create a new user and try logging in as that new user.

**Comment by SamGreenwood1** [comment]
I followed the instructions you gave me [here](https://github.com/naztronaut/RaspberryPi-Website-Uptime-Monitor/issues/5#issuecomment-777233254). Is there a way I could change the password?

**Comment by naztronaut** [comment]
In the instructions, I had you create a "root" user, not "admin" - I gave a quick and dirty set of steps too because I thought you had more experience with set ups so I didn't cover every detail. Check out https://raspberrytips.com/install-mariadb-raspberry-pi/ - more details and screenshots there, that should be helpful.

**Comment by SamGreenwood1** [comment]
Oh ok

**Comment by SamGreenwood1** [comment]
@naztronaut password changed what do I do now?

**Comment by SamGreenwood1** [comment]
would I need to run `GRANT ALL PRIVILEGES ON <dbname>.* TO '<username>'@'localhost';' for the admin user?

**Comment by SamGreenwood1** [comment]
should the first variable in db.py be set to MySQLdb or should I change it to the name of the db?

**Comment by SamGreenwood1** [comment]
now I'm getting these errors:

![Screenshot 2021-03-18 130452](https://user-images.githubusercontent.com/20076209/111667047-b5f8a380-87ea-11eb-8715-2b994e63b169.png)

it looks to me like MySQL isn't accessible by cronTab for some reason. I've checked it's not updating the `crontab -e` file,
